# Generated by Django 6.0.3 on 2026-04-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
