# Generated by Django 6.0.3 on 2026-04-24 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_route_distance'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Procesando'), ('COMPLETED', 'Completado'), ('FAILED', 'Error')], default='PENDING', max_length=20),
        ),
    ]
